import { Navigation } from "@/components/Navigation/Navigation";
import "@/styles/globals.css";
import type { AppProps, NextWebVitalsMetric } from "next/app";
import Head from "next/head";
import { Roboto } from "next/font/google";
import Script from "next/script";
import dynamic from "next/dynamic";
import { axios } from "@/api/axiosInstance";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["italic"],
  subsets: ["latin"],
  display: "swap",
});

const DynamicNavigation = dynamic(() =>
  import("../components/Navigation/Navigation").then((mod) => mod.Navigation)
);

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>My app :D</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        {/* <style jsx global>{`
          html {
            font-family: ${roboto.style.fontFamily};
            font-style: ${roboto.style.fontStyle};
          }
        `}</style> */}
      </Head>
      <div className={roboto.className}>
        {/* <Navigation /> */}
        <DynamicNavigation />
        <Component {...pageProps} />
        {/* <Script
          src="../utils/script.js"
          onLoad={() => {
            console.log("Script has loaded");
          }}
        /> */}
        {/* <Script>{`console.log("loaded");`}</Script> */}
      </div>
    </>
  );
}

// export function reportWebVitals(metric: NextWebVitalsMetric) {
//   const body = JSON.stringify(metric);
//   const url = "http://localhost:4001/analytics";

//   if (navigator.sendBeacon) {
//     navigator.sendBeacon(url, body);
//   } else {
//     fetch(url, { body, method: "POST", keepalive: true });
//   }
//   // axios.post("/analytics", body);
// }
