import { Navigation } from "@/components/Navigation/Navigation";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { Roboto } from "next/font/google";
import Script from "next/script";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["italic"],
  subsets: ["latin"],
  display: "swap",
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>My app :D</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        {/* <style jsx global>{`
          html {
            font-family: ${roboto.style.fontFamily};
            font-style: ${roboto.style.fontStyle};
          }
        `}</style> */}
      </Head>
      <div className={roboto.className}>
        <Navigation />
        <Component {...pageProps} />
        {/* <Script
          src="../utils/script.js"
          onLoad={() => {
            console.log("Script has loaded");
          }}
        /> */}
        {/* <Script>{`console.log("loaded");`}</Script> */}
      </div>
    </>
  );
}
